event-threads: 2
worker-threads: 2
worker-monitor-threads: 1
worker-fs-threads: 2
worker-email-outbox-threads: 1
logger-level: debug

is-testing: true

server-port: 8080
monitor-server-port: 8081
dynamic-config-updates-enabled: false
dynamic-config-cache-path: /tmp/smirkly-auth-dynamic-config-cache.json
dynamic-config-server-url: http://localhost:8083/
dynamic-config-service-name: smirkly-auth
dynamic-config-update-interval: 5s
dynamic-config-full-update-interval: 1m
postgres-dbconnection: postgresql://smirkly_auth:smirkly_auth@localhost:5432/smirkly_auth

AUTH_JWT_AUDIENCE: smirkly-api
AUTH_JWT_KEY_ID: smirkly-auth-testing-rs256
AUTH_JWT_PRIVATE_KEY_PATH: ./third_party/cpp-jwt/examples/rsa_256/jwtRS256.key
AUTH_JWT_PUBLIC_KEY_PATH: ./third_party/cpp-jwt/examples/rsa_256/jwtRS256.key.pub
